## Script is used to loop through a CSV file, containing data on multiple
## devices, and generates separate configuration files for every unique device

import csv
from jinja2 import Template

source_file = "Switch-Interface.csv"
template_file = "Switch_Template_csv.j2"
configuration_file_name = ""

# Stores the entire configuration generated by Jinja
switch_configs = ""

with open(template_file) as f:
  interface_template = Template(f.read(), keep_trailing_newline=True)

with open(source_file) as f:
  reader = csv.DictReader(f)
  for row in reader:
    interface_config = interface_template.render(
      interface = row["interface"],
      vlan = row["vlan"],
      server = row["server"],
      link = row["link"],
      purpose = row["purpose"]
    )

    # Only executed on the first run to set the file name
    if (configuration_file_name == ""):
      configuration_file_name = row["hostname"]
      switch_configs += interface_config
    elif (configuration_file_name == row['hostname']):
      switch_configs += interface_config
    # Executes when a new device is detected (Different hostname)
    else:
      with open("{}_config.txt".format(configuration_file_name), "w") as f:
        f.write(switch_configs)
      configuration_file_name = row["hostname"]
      switch_configs = interface_config

# Due to limitation of CSV reader, unable to identify when the reader
# is on the last line. As such, without the code block below,
# configuration for the last device in the CSV file won't be written to the file
with open("{}_config.txt".format(configuration_file_name), "w") as f:
  f.write(switch_configs)
